repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1  # Use the ref you want to point at
    hooks:
    -   id: end-of-file-fixer

-   repo: git://github.com/doublify/pre-commit-clang-format
    rev: master
    hooks:
    -   id: clang-format
