exclude: version

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0  # Use the ref you want to point at
    hooks:
    - id: trailing-whitespace
      name: (Common) Remove trailing whitespaces
    - id: end-of-file-fixer
      name: (Common) Remove extra EOF newlines
    - id: check-yaml
      name: (YAML) Check syntax

#-   repo: https://github.com/executablebooks/mdformat
#    rev: 0.7.10
#    hooks:
#      - id: mdformat
#        name: (Markdown) Format with mdformat

-   repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
    -   id: clang-format
        always_run: true
        args: ["-i"]
        additional_dependencies: ["clang-format==12.0.1"]

-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.9.0
    hooks:
    -   id: black
        language_version: python
