[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pybind11>=2.8.0",
    "cmake>=3.21",
    "scikit-build>=0.12",
    "mypy; platform_system!='Windows'",
    "ninja; platform_system!='Windows'"
]

build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"
