name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-10.15, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - name: Checkout Copclib
      uses: actions/checkout@v2

    - uses: ilammy/msvc-dev-cmd@v1
      if: matrix.os == 'windows-latest'

    - name: Set up Conda for Python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        channels: conda-forge, defaults
        show-channel-urls: true
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}

    - name: Free up disk space
      if: ${{ runner.os == 'Linux' }}
      run: |
        sudo rm -rf /usr/share/dotnet

    - name: Setup Python (laz-perf)
      shell: bash -l {0}
      run: |
          conda update -n base -c defaults conda -y
          conda config --add channels conda-forge
          conda config --set channel_priority strict
          conda install -c conda-forge compilers -y
          conda install -c conda-forge ninja cmake -y
          conda install -c conda-forge laz-perf --only-deps -y
      continue-on-error: true

    - name: Setup Python (copc-lib)
      run: |
        conda install -c conda-forge Catch2 pybind11 --yes
        python -m pip install --upgrade pip
        pip install pytest wheel
      shell:
        bash -l {0}

    - name: Checkout Lazperf
      uses: actions/checkout@v2
      with:
        path: lazperf
        repository: hobu/laz-perf
        ref: 2.1.0

    - name: Build lazperf
      shell: bash -l {0}
      working-directory: lazperf
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          export CC=cl.exe
          export CXX=cl.exe
        fi
        mkdir build
        cd build
        cmake .. -G Ninja -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -Dgtest_force_shared_crt=ON
        cmake --build . --config ${{env.BUILD_TYPE}}
        if [ "$RUNNER_OS" == "Windows" ]; then
          cmake --install .
        else
          sudo cmake --install .
        fi

    - name: Build Copclib Python Bindings
      run: |
        python -m pip install .
        pip list
        conda list
      shell:
        bash -l {0}

    - name: Test Copclib Python Bindings
      run: |
        pip list
        conda list
        cd test
        curl -L -O https://cloudfront.rockrobotic.com/public/laz-examples/copc/drafts/span/autzen-classified.copc.laz
        python ../example/example-reader.py
        pytest
        python ../example/example-reader.py
        python ../example/example-writer.py
      shell:
        bash -l {0}

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -G Ninja -B "${{github.workspace}}/build" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DWITH_TESTS_AND_EXAMPLES=ON -DWITH_PYTHON=OFF
      shell:
        bash -l {0}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build "${{github.workspace}}/build" --config ${{env.BUILD_TYPE}}
      shell:
        bash -l {0}

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure
      shell:
        bash -l {0}
